"""empty message

Revision ID: 824c1d364b7a
Revises: 
Create Date: 2019-04-12 15:02:38.545774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '824c1d364b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'stu_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_index('stu_id', table_name='user_info')
    op.drop_column('user_info', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.create_index('stu_id', 'user_info', ['stu_id'], unique=True)
    op.alter_column('user_info', 'stu_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
